name: CD

on:
  push:
    tags:
    - "v*.*.*"

jobs:
  build-release:
    name: "Build release"
    strategy:
      matrix:
        release: [linux, windows, mac]
        include:
        - release: linux
          os: ubuntu-latest
          target: x86_64-unknown-linux-gnu
        - release: windows
          os: windows-latest
          target: x86_64-pc-windows-gnu
        - release: mac
          os: macos-latest
          target: x86_64-apple-darwin
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Install Rust toolchain
      run: |
        rustup update --no-self-update stable
        rustup target add ${{ matrix.target }}

    - name: Cache Dependencies
      uses: Swatinem/rust-cache@v2

    - name: Build binaries
      run: cargo build --target=${{ matrix.target }} --release
    
    - name: Move binaries (linux, mac)
      run: |
          mkdir ${{ matrix.target }} &&
          cp target/${{ matrix.target }}/release/geoff ${{ matrix.target }} &&
          cp README.md ${{ matrix.target }} &&
          tar -czvf ${{ matrix.target }}.tar.gz ${{ matrix.target }}
      if: startsWith(matrix.os, 'macos-') || startsWith(matrix.os, 'ubuntu-')
    
    - name: Move binaries (windows)
      run: |
          mkdir ${{ matrix.target }} &&
          cp target/${{ matrix.target }}/release/geoff.exe ${{ matrix.target }} &&
          cp README.md ${{ matrix.target }} &&
          tar -czvf ${{ matrix.target }}.tar.gz ${{ matrix.target }}
      if: startsWith(matrix.os, 'windows-')
      
    - name: Archive zip
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.os }}-binary
        path: ${{ matrix.target }}.tar.gz

  release-upload:
    name: "Upload release asset"
    needs: build-release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download archives
      uses: actions/download-artifact@v3
    
    - name: Upload release asset
      id: upload_release_asset
      uses: softprops/action-gh-release@v1
      with: 
        files: |
          macos-latest-binary.tar.gz
          linux-latest-binary.tar.gz
          windows-latest-binary.tar.gz
